---
- name: Configure elasticsearch.yml File
  copy:
    src: '{{item.src}}'
    dest: /etc/elasticesearch/elasticsearch.yml
    owner: root
    group: elasticsearch
  with_items:
    - { src: 'path/to/your/conf/file.yml'}
